# This is a basic workflow that is manually triggered

name: local branch testing workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

    # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup_build_test:
    runs-on: self-hosted
    steps:
      - run: |
          echo "Branch to run: ${{ github.event.inputs.branchName }}"
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: mvn -U -B -e clean install -DskipTests

      - name: unit test run
        run: |
          cd activemq-unit-tests
          mvn -B -e -fae test -Dsurefire.rerunFailingTestsCount=3
